# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 23:19
from __future__ import unicode_literals

import calparks.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('park_type', models.CharField(blank=True, max_length=100)),
                ('park_size', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator])),
                ('average_user_rec', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Park Information',
                'verbose_name_plural': 'Park Information',
            },
        ),
        migrations.CreateModel(
            name='UserRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('user_rating', models.PositiveSmallIntegerField(default=1, null=True, validators=[calparks.models.validate_ratings])),
                ('rec_timestamp', models.DateTimeField(default=datetime.datetime.now, editable=False, null=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calparks.ParkInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recommendation',
                'verbose_name_plural': 'User Recommendations',
            },
        ),
    ]
